/* eslint-disable no-template-curly-in-string */
import type { Route } from '../src/compiler'
import { describe, expect, it } from 'vitest'
import { compileRoutes } from '../src/compiler'
import { DynamicParam, WildcardParam } from '../src/tree'

const api: Route[] = [
  { segments: ['/api', '/health'], metadata: { GET: { responseType: '{ status: \'ok\' }' } } },
  { segments: ['/api', '/users'], metadata: { GET: { responseType: 'User[]' }, POST: { bodyType: '{ name: string }', responseType: 'User', errorResponseType: '{ message: string }' } } },
  { segments: ['/api', '/users', DynamicParam], metadata: { GET: { responseType: 'User' } } },
  { segments: ['/api', '/files', WildcardParam], metadata: { GET: { responseType: 'Blob' } } },
  { segments: ['/api', '/ping'], metadata: { ALL: { responseType: '\'pong\'' } } },
]

describe('compileRoutes', () => {
  it('emits a module of types specialised to the routes', () => {
    expect(compileRoutes([{ routes: api }]).code).toMatchInlineSnapshot(`
      "// generated by fetchdts, strategy table+union, 5 routes
      // (3 static, 1 dynamic, 1 wildcard)
      import type { AnyHTTPMethod, DynamicParam, Endpoint, HTTPMethod, TypedFetchErrorBody, TypedFetchMethods, TypedFetchRequestBody, TypedFetchRequestHeaders, TypedFetchRequestQuery, TypedFetchRequires, TypedFetchResponseBody, TypedFetchResponseHeaders, ValidFetchInput, WildcardParam } from 'fetchdts'

      export interface Routes {
        "/api": {
          "/health": {
            [Endpoint]: {
              "GET": {
                "response": { status: 'ok' }
              }
            }
          }
          "/users": {
            [DynamicParam]: {
              [Endpoint]: {
                "GET": {
                  "response": User
                }
              }
            }
            [Endpoint]: {
              "GET": {
                "response": User[]
              }
              "POST": {
                "body": { name: string }
                "response": User
                "errorResponse": { message: string }
              }
            }
          }
          "/files": {
            [WildcardParam]: {
              [Endpoint]: {
                "GET": {
                  "response": Blob
                }
              }
            }
          }
          "/ping": {
            [Endpoint]: Record<HTTPMethod, {
              "response": 'pong'
            }>
          }
        }
      }

      /**
       * Every path whose every segment is known, mapped to the endpoints registered on it.
       *
       * A fast path rather than the authority: a lookup that misses falls through to the tree, which
       * costs nothing, since a path reached through a parameter has to walk either way.
       */
      export interface Exact {
        "/api/health": Routes["/api"]["/health"][typeof Endpoint]
        "/api/users": Routes["/api"]["/users"][typeof Endpoint]
        "/api/ping": Routes["/api"]["/ping"][typeof Endpoint]
      }

      export type Path =
        | "/api/health"
        | "/api/users"
        | \`/api/users/\${string}\${string}\`
        | \`/api/files/\${string}\${string}\`
        | "/api/files"
        | "/api/ping"

      /**
       * Whether a path resolves, for use in parameter position: \`input: T & ValidInput<T, M>\`.
       *
       * Does not consult \`Exact\`: a lookup where the path is still a type parameter relates a \`keyof\`
       * of every static path once per program, so the table stays where the path is resolved.
       */
      export type ValidInput<Path_, Method extends AnyHTTPMethod = 'GET'>
        = ValidFetchInput<Routes, Path_, Method>

      export type Response<Path_, Method extends AnyHTTPMethod = 'GET'>
        = Path_ extends keyof Exact
          ? Uppercase<Method> extends keyof Exact[Path_]
            ? 'response' extends keyof Exact[Path_][Uppercase<Method>]
              ? Exact[Path_][Uppercase<Method>]['response']
              : unknown
            : TypedFetchResponseBody<Routes, Path_, Method>
          : TypedFetchResponseBody<Routes, Path_, Method>

      export type Methods<Path_> = TypedFetchMethods<Routes, Path_>

      export type ResponseHeaders<Path_, Method extends AnyHTTPMethod = 'GET'> = TypedFetchResponseHeaders<Routes, Path_, Method>

      export type ErrorBody<Path_, Method extends AnyHTTPMethod = 'GET'> = TypedFetchErrorBody<Routes, Path_, Method>

      export type RequestBody<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = BodyInit | null> = TypedFetchRequestBody<Routes, Path_, Method, Fallback>

      export type RequestQuery<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = Record<string, unknown>> = TypedFetchRequestQuery<Routes, Path_, Method, Fallback>

      export type RequestHeaders<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = HeadersInit> = TypedFetchRequestHeaders<Routes, Path_, Method, Fallback>

      export type Requires<Path_, Method extends AnyHTTPMethod, Field extends 'body' | 'query' | 'headers'> = TypedFetchRequires<Routes, Path_, Method, Field>"
    `)
  })

  it('reports the names it imports, for a consumer that re-exports them', () => {
    const compiled = compileRoutes([{ routes: api }], { moduleSpecifier: 'nuxt/app' })
    expect(compiled.imports).toContain('ValidFetchInput')
    expect(compiled.imports).toContain('TypedFetchMethods')
    expect(compiled.imports).toContain('Endpoint')
    expect(compiled.imports).toEqual([...compiled.imports].sort())
    for (const name of compiled.imports) {
      expect(compiled.code).toContain(name)
    }
    expect(compiled.code.split('\n').find(line => line.startsWith('import type'))).toBe(
      `import type { ${compiled.imports.join(', ')} } from 'nuxt/app'`,
    )
  })

  it('reports the strategy it chose and the counts that chose it', () => {
    const compiled = compileRoutes([{ routes: api }])
    expect(compiled.strategy).toBe('table+union')
    expect(compiled.stats).toEqual({ routes: 5, static: 3, dynamic: 1, wildcard: 1 })
    expect(compiled.code).toContain('strategy table+union')
    expect(String(compiled)).toBe(compiled.code)
  })

  it('drops the path union where the parameters would make it expensive', () => {
    const many: Route[] = Array.from({ length: 30 }, (_, i) => ({
      segments: [`/api/route${i}`, DynamicParam],
      metadata: { GET: { responseType: `${i}` } },
    }))
    const compiled = compileRoutes([{ routes: many }], { unionLimit: 10 })
    expect(compiled.strategy).toBe('tree')
    // the same name is emitted whichever strategy is chosen, so a consumer's signature is unaffected
    expect(compiled.code).toContain('export type Path = AnyFetchPath')
    expect(compiled.code).toContain('export type ValidInput<')
  })

  it('takes a forced strategy', () => {
    expect(compileRoutes([{ routes: api }], { strategy: 'tree+union' }).code).not.toContain('interface Exact')
    expect(compileRoutes([{ routes: api }], { strategy: 'tree+union' }).code).toContain('export type Path =\n')
  })

  it('keeps every parameter of a route in the emitted path', () => {
    const compiled = compileRoutes([{ routes: [
      { segments: ['/a', DynamicParam, '/b', DynamicParam, '/c'], metadata: { GET: { responseType: '1' } } },
      { segments: ['/f', WildcardParam], metadata: { GET: { responseType: '2' } } },
    ] }])
    // a static segment between two parameters keeps its place, and a wildcard may consume nothing
    expect(compiled.code).toContain('| `/a/${string}${string}/b/${string}${string}/c`')
    expect(compiled.code).toContain('| `/f/${string}${string}`')
    expect(compiled.code).toContain('| "/f"')
  })

  it('emits the root for a wildcard that consumes the whole path', () => {
    const compiled = compileRoutes([{ routes: [{ segments: [WildcardParam], metadata: { GET: { responseType: 'Any' } } }] }])
    expect(compiled.code).toContain('| "/"')
    expect(compiled.code).not.toContain('| ""')
  })

  it('emits a route with no segments as the root', () => {
    const compiled = compileRoutes([{ routes: [{ segments: ['/'], metadata: { GET: { responseType: 'Home' } } }] }])
    expect(compiled.code).toContain('"/": Routes[typeof Endpoint]')
    expect(compiled.code).toContain('| "/"')
    expect(compiled.code).not.toContain('"":')
  })

  it('normalises method keys, which a router compares case-insensitively', () => {
    const compiled = compileRoutes([{ routes: [{ segments: ['/a'], metadata: { get: { responseType: '1' } } as never }] }])
    expect(compiled.code).toContain('"GET"')
  })

  it('rejects a segment after a wildcard, which consumes the remainder of a path', () => {
    expect(() => compileRoutes([{ routes: [{ segments: [WildcardParam, '/tail'], metadata: { GET: { responseType: '1' } } }] }]))
      .toThrow(/after a wildcard/)
  })

  it('compiles several sets into one module, keyed by origin', () => {
    const compiled = compileRoutes([
      { routes: [{ segments: ['/api', '/health'], metadata: { GET: { responseType: 'Health' } } }] },
      { routes: [{ segments: ['/v1', '/posts'], metadata: { GET: { responseType: 'Post[]' } } }], origin: 'https://api.example.com' },
    ])
    expect(compiled.code).toContain('"https://api.example.com"')
    expect(compiled.code).toContain('"/api/health": Routes["/api"]["/health"][typeof Endpoint]')
    expect(compiled.code).toContain('"https://api.example.com/v1/posts"')
  })

  it('resolves against another interface, for a route map that can be extended by hand', () => {
    const compiled = compileRoutes([{ routes: api }], { name: 'GeneratedRoutes', resolveAgainst: 'ServerRoutes' })
    // the table still points into the emitted tree, so a generated path keeps the lookup
    expect(compiled.code).toContain('"/api/health": GeneratedRoutes["/api"]["/health"][typeof Endpoint]')
    // the walk behind it goes through the interface a consumer can augment
    expect(compiled.code).toContain('ValidFetchInput<ServerRoutes, Path_, Method>')
    expect(compiled.code).toContain('TypedFetchResponseBody<ServerRoutes, Path_, Method>')
    expect(compiled.code).not.toContain('TypedFetchResponseBody<GeneratedRoutes,')
    expect(() => compileRoutes([{ routes: api }], { resolveAgainst: 'not an identifier' })).toThrow(/not a valid interface name/)
  })

  it('rejects a name the emitted module declares itself', () => {
    expect(() => compileRoutes([{ routes: api }], { name: 'Response' })).toThrow(/declares itself/)
    expect(() => compileRoutes([{ routes: api }], { resolveAgainst: 'Exact' })).toThrow(/declares itself/)
  })

  it('emits extra imports after its own, keeping the banner first', () => {
    const compiled = compileRoutes([{ routes: api }], { imports: ['import type { Serialize } from \'nuxt/app\''] })
    const lines = compiled.code.split('\n')
    expect(lines[0]).toContain('generated by fetchdts')
    expect(lines[2]).toContain('from \'fetchdts\'')
    expect(lines[3]).toBe('import type { Serialize } from \'nuxt/app\'')
  })

  it('takes a name and a module specifier', () => {
    const compiled = compileRoutes([{ routes: api }], { name: 'ServerRoutes', moduleSpecifier: 'nuxt/app' })
    expect(compiled.code).toContain('from \'nuxt/app\'')
    expect(compiled.code).toContain('export interface ServerRoutes {')
    expect(compiled.code).toContain('TypedFetchResponseBody<ServerRoutes,')
  })
})
