shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
overrides:
  fetchdts: 'link:.'
ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
onlyBuiltDependencies:
  - simple-git-hooks
