// generated by fetchdts, strategy table+union, 12 routes
// (7 static, 4 dynamic, 1 wildcard)
import type { AnyHTTPMethod, DynamicParam, Endpoint, HTTPMethod, TypedFetchErrorBody, TypedFetchMethods, TypedFetchRequestBody, TypedFetchRequestHeaders, TypedFetchRequestQuery, TypedFetchRequires, TypedFetchResponseBody, TypedFetchResponseHeaders, ValidFetchInput, WildcardParam } from 'fetchdts'
import type { ExtensibleRoutes } from './extensible'

export interface CompiledRoutes {
  "/api": {
    "/health": {
      [Endpoint]: {
        "GET": {
          "response": { status: 'ok' }
        }
      }
    }
    "/users": {
      [DynamicParam]: {
        "/posts": {
          [Endpoint]: {
            "GET": {
              "response": { title: string }[]
            }
          }
        }
        [Endpoint]: {
          "GET": {
            "response": { id: number, name: string }
            "responseHeaders": { 'x-cache': 'hit' | 'miss' }
          }
        }
      }
      [Endpoint]: {
        "GET": {
          "response": { id: number }[]
        }
        "POST": {
          "body": { name: string }
          "response": { id: number }
          "errorResponse": { message: string }
        }
      }
    }
    "/comments": {
      "/latest": {
        [Endpoint]: {
          "GET": {
            "response": { latest: true }
          }
        }
      }
      [DynamicParam]: {
        [Endpoint]: {
          "GET": {
            "response": { body: string }
          }
        }
      }
    }
    "/ping": {
      [Endpoint]: Record<HTTPMethod, {
        "response": 'pong'
      }>
    }
    "/search": {
      [Endpoint]: Record<Exclude<HTTPMethod, "POST">, {
        "response": { results: string[] }
      }> & {
        "POST": {
          "body": { query: string }
          "response": { results: string[], total: number }
        }
      }
    }
    "/proxy": {
      [Endpoint]: Record<HTTPMethod, {
      }>
    }
    "/files": {
      [WildcardParam]: {
        [Endpoint]: {
          "GET": {
            "response": Blob
          }
        }
      }
    }
  }
  "https://api.example.com": {
    "/v1": {
      "/posts": {
        [DynamicParam]: {
          [Endpoint]: {
            "GET": {
              "response": { id: number }
            }
          }
        }
        [Endpoint]: {
          "GET": {
            "response": { id: number }[]
          }
        }
      }
    }
  }
}

/**
 * Every path whose every segment is known, mapped to the endpoints registered on it.
 *
 * A fast path rather than the authority: a lookup that misses falls through to the tree, which
 * costs nothing, since a path reached through a parameter has to walk either way.
 */
export interface Exact {
  "/api/health": CompiledRoutes["/api"]["/health"][typeof Endpoint]
  "/api/users": CompiledRoutes["/api"]["/users"][typeof Endpoint]
  "/api/comments/latest": CompiledRoutes["/api"]["/comments"]["/latest"][typeof Endpoint]
  "/api/ping": CompiledRoutes["/api"]["/ping"][typeof Endpoint]
  "/api/search": CompiledRoutes["/api"]["/search"][typeof Endpoint]
  "/api/proxy": CompiledRoutes["/api"]["/proxy"][typeof Endpoint]
  "https://api.example.com/v1/posts": CompiledRoutes["https://api.example.com"]["/v1"]["/posts"][typeof Endpoint]
}

export type Path =
  | "/api/health"
  | "/api/users"
  | `/api/users/${string}${string}`
  | `/api/users/${string}${string}/posts`
  | "/api/comments/latest"
  | `/api/comments/${string}${string}`
  | "/api/ping"
  | "/api/search"
  | "/api/proxy"
  | `/api/files/${string}${string}`
  | "/api/files"
  | "https://api.example.com/v1/posts"
  | `https://api.example.com/v1/posts/${string}${string}`

/**
 * Whether a path resolves, for use in parameter position: `input: T & ValidInput<T, M>`.
 *
 * Does not consult `Exact`. A validator sits where the path is still a type parameter, so a
 * lookup there relates a `keyof` of every static path once per program and grows with the route
 * set; the table stays where the path is resolved, which is the response.
 */
export type ValidInput<Path_, Method extends AnyHTTPMethod = 'GET'>
  = ValidFetchInput<ExtensibleRoutes, Path_, Method>

export type Response<Path_, Method extends AnyHTTPMethod = 'GET'>
  = Path_ extends keyof Exact
    ? Uppercase<Method> extends keyof Exact[Path_]
      ? 'response' extends keyof Exact[Path_][Uppercase<Method>]
        ? Exact[Path_][Uppercase<Method>]['response']
        : unknown
      : TypedFetchResponseBody<ExtensibleRoutes, Path_, Method>
    : TypedFetchResponseBody<ExtensibleRoutes, Path_, Method>

export type Methods<Path_> = TypedFetchMethods<ExtensibleRoutes, Path_>

export type ResponseHeaders<Path_, Method extends AnyHTTPMethod = 'GET'> = TypedFetchResponseHeaders<ExtensibleRoutes, Path_, Method>

export type ErrorBody<Path_, Method extends AnyHTTPMethod = 'GET'> = TypedFetchErrorBody<ExtensibleRoutes, Path_, Method>

export type RequestBody<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = BodyInit | null> = TypedFetchRequestBody<ExtensibleRoutes, Path_, Method, Fallback>

export type RequestQuery<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = Record<string, unknown>> = TypedFetchRequestQuery<ExtensibleRoutes, Path_, Method, Fallback>

export type RequestHeaders<Path_, Method extends AnyHTTPMethod = 'GET', Fallback = HeadersInit> = TypedFetchRequestHeaders<ExtensibleRoutes, Path_, Method, Fallback>

export type Requires<Path_, Method extends AnyHTTPMethod, Field extends 'body' | 'query' | 'headers'> = TypedFetchRequires<ExtensibleRoutes, Path_, Method, Field>
